export { Capabilities } from './Capabilities'
export { Hero } from './Hero'
export { NairobiBand } from './NairobiBand'
export { getHomePage } from './queries'
export { StoryScroll } from './StoryScroll'
export { TechStrip } from './TechStrip'
export { WhyOqtekal } from './WhyOqtekal'
