/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    subscribers: Subscriber;
    products: Product;
    pillars: Pillar;
    services: Service;
    'hosting-plans': HostingPlan;
    'case-studies': CaseStudy;
    'team-members': TeamMember;
    testimonials: Testimonial;
    clients: Client;
    posts: Post;
    jobs: Job;
    pages: Page;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    pillars: {
      services: 'services';
    };
  };
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pillars: PillarsSelect<false> | PillarsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'hosting-plans': HostingPlansSelect<false> | HostingPlansSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  status: 'new' | 'contacted' | 'won' | 'lost' | 'spam';
  type: 'project' | 'demo' | 'hosting' | 'career' | 'general';
  name: string;
  company?: string | null;
  email: string;
  phone?: string | null;
  message: string;
  budget?: string | null;
  interest?: string | null;
  sourcePage?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Short promise, e.g. "Every customer conversation, one inbox."
   */
  tagline: string;
  /**
   * Two sentences shown on product cards.
   */
  summary: string;
  /**
   * e.g. "Communications", "Education"
   */
  category: string;
  availability: 'live' | 'beta' | 'soon';
  /**
   * Product logo (transparent PNG or SVG). Optional.
   */
  logo?: (number | null) | Media;
  /**
   * Third-party logo shown as "Integrates with…" (e.g. the official M-Pesa logo). Use only official, unmodified files.
   */
  partnerLogo?: (number | null) | Media;
  /**
   * Built-in product illustration used until real screenshots are uploaded below.
   */
  visual: 'comms' | 'school' | 'property' | 'erp' | 'sports' | 'payments' | 'pos';
  /**
   * Real screenshots. The first one replaces the built-in illustration.
   */
  screenshots?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. https://tolkyn.co.ke (optional)
   */
  externalUrl?: string | null;
  problem: string;
  features?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  audiences?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  integrations?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        /**
         * e.g. "5 channels"
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "From KES 4,500 / month" (optional)
   */
  pricingNote?: string | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. How this page appears on Google and when shared on WhatsApp, LinkedIn, etc.
   */
  seo?: {
    /**
     * Up to ~60 characters. Defaults to the page title.
     */
    title?: string | null;
    /**
     * Up to ~155 characters. Defaults to the summary.
     */
    description?: string | null;
    /**
     * Share image, 1200×630. A branded image is generated if empty.
     */
    image?: (number | null) | Media;
  };
  /**
   * The web address of this item. Leave empty to generate it from the title.
   */
  slug: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  /**
   * Untick once this item contains real, approved information.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is in the image, e.g. "Tolkyn inbox showing WhatsApp chats".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The main groups shown on the Services page (e.g. "Cloud & Hosting").
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars".
 */
export interface Pillar {
  id: number;
  title: string;
  /**
   * One or two sentences shown in lists and menus.
   */
  summary: string;
  /**
   * Opening paragraph on this group's own page.
   */
  intro?: string | null;
  /**
   * Services in this group. Add a service and choose this group to list it here.
   */
  services?: {
    docs?: (number | Service)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * The web address of this item. Leave empty to generate it from the title.
   */
  slug: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Optional. How this page appears on Google and when shared on WhatsApp, LinkedIn, etc.
   */
  seo?: {
    /**
     * Up to ~60 characters. Defaults to the page title.
     */
    title?: string | null;
    /**
     * Up to ~155 characters. Defaults to the summary.
     */
    description?: string | null;
    /**
     * Share image, 1200×630. A branded image is generated if empty.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  pillar: number | Pillar;
  /**
   * One sentence shown in lists and menus.
   */
  summary: string;
  /**
   * Big heading on the service page. Defaults to the title.
   */
  headline?: string | null;
  intro: string;
  deliverables?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  outcomes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tools and platforms we use for this service.
   */
  technologies?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  relatedProducts?: (number | Product)[] | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. How this page appears on Google and when shared on WhatsApp, LinkedIn, etc.
   */
  seo?: {
    /**
     * Up to ~60 characters. Defaults to the page title.
     */
    title?: string | null;
    /**
     * Up to ~155 characters. Defaults to the summary.
     */
    description?: string | null;
    /**
     * Share image, 1200×630. A branded image is generated if empty.
     */
    image?: (number | null) | Media;
  };
  /**
   * The web address of this item. Leave empty to generate it from the title.
   */
  slug: string;
  /**
   * Set automatically.
   */
  path?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Untick once this item contains real, approved information.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hosting-plans".
 */
export interface HostingPlan {
  id: number;
  name: string;
  category: 'web' | 'vps' | 'email';
  /**
   * Who it is for, in one line.
   */
  tagline: string;
  priceMonthly: number;
  /**
   * Leave empty to use 10× the monthly price.
   */
  priceYearly?: number | null;
  /**
   * e.g. Storage → 50 GB NVMe
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  client: string;
  industry: string;
  year?: number | null;
  /**
   * One or two sentences for cards.
   */
  summary: string;
  cover?: (number | null) | Media;
  results?:
    | {
        /**
         * e.g. "3×" or "40 s"
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  challenge: string;
  solution: string;
  approach?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  outcome?: string | null;
  product?: (number | null) | Product;
  services?: (number | Service)[] | null;
  stack?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  testimonial?: (number | null) | Testimonial;
  /**
   * Optional. How this page appears on Google and when shared on WhatsApp, LinkedIn, etc.
   */
  seo?: {
    /**
     * Up to ~60 characters. Defaults to the page title.
     */
    title?: string | null;
    /**
     * Up to ~155 characters. Defaults to the summary.
     */
    description?: string | null;
    /**
     * Share image, 1200×630. A branded image is generated if empty.
     */
    image?: (number | null) | Media;
  };
  /**
   * The web address of this item. Leave empty to generate it from the title.
   */
  slug: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  /**
   * Untick once this item contains real, approved information.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Only publish quotes you have permission to use.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  role?: string | null;
  company?: string | null;
  photo?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Untick once this item contains real, approved information.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People shown in the Team section. Use portraits with the same background and lighting.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  /**
   * Portrait, at least 1000px tall. Set the focal point on the face.
   */
  photo?: (number | null) | Media;
  /**
   * One line, e.g. "Turns business processes into reliable systems."
   */
  focus: string;
  /**
   * 2–4 sentences.
   */
  bio: string;
  expertise?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  links?: {
    /**
     * Full URL
     */
    linkedin?: string | null;
    x?: string | null;
    github?: string | null;
    email?: string | null;
  };
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Untick once this item contains real, approved information.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logos in the "Trusted by" strip. Only add clients who agreed to be listed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * Single-colour or transparent logo works best.
   */
  logo?: (number | null) | Media;
  url?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Untick once this item contains real, approved information.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Two sentences shown on the Insights page.
   */
  excerpt: string;
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. How this page appears on Google and when shared on WhatsApp, LinkedIn, etc.
   */
  seo?: {
    /**
     * Up to ~60 characters. Defaults to the page title.
     */
    title?: string | null;
    /**
     * Up to ~155 characters. Defaults to the summary.
     */
    description?: string | null;
    /**
     * Share image, 1200×630. A branded image is generated if empty.
     */
    image?: (number | null) | Media;
  };
  /**
   * The web address of this item. Leave empty to generate it from the title.
   */
  slug: string;
  category: 'engineering' | 'product' | 'payments' | 'cloud' | 'company';
  author?: (number | null) | TeamMember;
  publishedAt: string;
  /**
   * Untick once this item contains real, approved information.
   */
  isPlaceholder?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  location: string;
  type: 'full-time' | 'contract' | 'internship';
  summary: string;
  responsibilities?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  isOpen?: boolean | null;
  /**
   * The web address of this item. Leave empty to generate it from the title.
   */
  slug: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pages shown at /legal/<slug>, e.g. privacy and terms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. How this page appears on Google and when shared on WhatsApp, LinkedIn, etc.
   */
  seo?: {
    /**
     * Up to ~60 characters. Defaults to the page title.
     */
    title?: string | null;
    /**
     * Up to ~155 characters. Defaults to the summary.
     */
    description?: string | null;
    /**
     * Share image, 1200×630. A branded image is generated if empty.
     */
    image?: (number | null) | Media;
  };
  /**
   * The web address of this item. Leave empty to generate it from the title.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor' | 'sales')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pillars';
        value: number | Pillar;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'hosting-plans';
        value: number | HostingPlan;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  status?: T;
  type?: T;
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  message?: T;
  budget?: T;
  interest?: T;
  sourcePage?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  summary?: T;
  category?: T;
  availability?: T;
  logo?: T;
  partnerLogo?: T;
  visual?: T;
  screenshots?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  externalUrl?: T;
  problem?: T;
  features?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  audiences?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  integrations?:
    | T
    | {
        name?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  pricingNote?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars_select".
 */
export interface PillarsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  intro?: T;
  services?: T;
  slug?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  pillar?: T;
  summary?: T;
  headline?: T;
  intro?: T;
  deliverables?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  relatedProducts?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  path?: T;
  order?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hosting-plans_select".
 */
export interface HostingPlansSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  tagline?: T;
  priceMonthly?: T;
  priceYearly?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  features?:
    | T
    | {
        label?: T;
        id?: T;
      };
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  industry?: T;
  year?: T;
  summary?: T;
  cover?: T;
  results?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  challenge?: T;
  solution?: T;
  approach?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  outcome?: T;
  product?: T;
  services?: T;
  stack?:
    | T
    | {
        name?: T;
        id?: T;
      };
  testimonial?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  focus?: T;
  bio?: T;
  expertise?:
    | T
    | {
        label?: T;
        id?: T;
      };
  links?:
    | T
    | {
        linkedin?: T;
        x?: T;
        github?: T;
        email?: T;
      };
  order?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  company?: T;
  photo?: T;
  order?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  order?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  isPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  location?: T;
  type?: T;
  summary?: T;
  responsibilities?:
    | T
    | {
        text?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  isOpen?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    eyebrow?: string | null;
    /**
     * The main headline.
     */
    heading: string;
    text: string;
    primaryLabel?: string | null;
    secondaryLabel?: string | null;
  };
  productsIntro: {
    eyebrow?: string | null;
    heading: string;
    text?: string | null;
  };
  servicesIntro: {
    eyebrow?: string | null;
    heading: string;
    text?: string | null;
  };
  workIntro: {
    eyebrow?: string | null;
    heading: string;
    text?: string | null;
  };
  processIntro: {
    eyebrow?: string | null;
    heading: string;
    text?: string | null;
  };
  teamIntro: {
    eyebrow?: string | null;
    heading: string;
    text?: string | null;
  };
  hostingIntro: {
    eyebrow?: string | null;
    heading: string;
    text?: string | null;
  };
  ctaIntro: {
    eyebrow?: string | null;
    heading: string;
    text?: string | null;
  };
  process?:
    | {
        title: string;
        text: string;
        /**
         * e.g. "1–2 weeks"
         */
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heading: string;
  intro: string;
  story?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  values?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  commitments?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact details, social links and company facts used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  email: string;
  /**
   * Shown as written, e.g. +254 700 000 000
   */
  phone: string;
  /**
   * Digits only with country code, e.g. 254700000000
   */
  whatsapp: string;
  address: string;
  hours?: string | null;
  mapUrl?: string | null;
  socials?:
    | {
        platform: 'linkedin' | 'x' | 'facebook' | 'instagram' | 'youtube' | 'tiktok' | 'github' | 'whatsapp';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the home and about pages, e.g. "40+" / "Systems delivered".
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  statsArePlaceholder?: boolean | null;
  announcementEnabled?: boolean | null;
  announcementText?: string | null;
  announcementLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
        primaryLabel?: T;
        secondaryLabel?: T;
      };
  productsIntro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
      };
  servicesIntro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
      };
  workIntro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
      };
  processIntro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
      };
  teamIntro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
      };
  hostingIntro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
      };
  ctaIntro?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
      };
  process?:
    | T
    | {
        title?: T;
        text?: T;
        duration?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  story?:
    | T
    | {
        text?: T;
        id?: T;
      };
  values?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  commitments?:
    | T
    | {
        text?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  hours?: T;
  mapUrl?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  statsArePlaceholder?: T;
  announcementEnabled?: T;
  announcementText?: T;
  announcementLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}